// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "userapi/models"
)

// CreateOneCreatedCode is the HTTP code returned for type CreateOneCreated
const CreateOneCreatedCode int = 201

/*CreateOneCreated Created

swagger:response createOneCreated
*/
type CreateOneCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewCreateOneCreated creates CreateOneCreated with default headers values
func NewCreateOneCreated() *CreateOneCreated {

	return &CreateOneCreated{}
}

// WithPayload adds the payload to the create one created response
func (o *CreateOneCreated) WithPayload(payload *models.User) *CreateOneCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create one created response
func (o *CreateOneCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOneCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateOneBadRequestCode is the HTTP code returned for type CreateOneBadRequest
const CreateOneBadRequestCode int = 400

/*CreateOneBadRequest Invalid Form Data - Bad Request

swagger:response createOneBadRequest
*/
type CreateOneBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOneBadRequest creates CreateOneBadRequest with default headers values
func NewCreateOneBadRequest() *CreateOneBadRequest {

	return &CreateOneBadRequest{}
}

// WithPayload adds the payload to the create one bad request response
func (o *CreateOneBadRequest) WithPayload(payload *models.Error) *CreateOneBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create one bad request response
func (o *CreateOneBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOneBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
