// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "userapi/models"
)

// CreateOneCreatedCode is the HTTP code returned for type CreateOneCreated
const CreateOneCreatedCode int = 201

/*CreateOneCreated Created

swagger:response createOneCreated
*/
type CreateOneCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewCreateOneCreated creates CreateOneCreated with default headers values
func NewCreateOneCreated() *CreateOneCreated {

	return &CreateOneCreated{}
}

// WithPayload adds the payload to the create one created response
func (o *CreateOneCreated) WithPayload(payload *models.User) *CreateOneCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create one created response
func (o *CreateOneCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOneCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateOneDefault An error occured (POST user)

swagger:response createOneDefault
*/
type CreateOneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOneDefault creates CreateOneDefault with default headers values
func NewCreateOneDefault(code int) *CreateOneDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateOneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create one default response
func (o *CreateOneDefault) WithStatusCode(code int) *CreateOneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create one default response
func (o *CreateOneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create one default response
func (o *CreateOneDefault) WithPayload(payload *models.Error) *CreateOneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create one default response
func (o *CreateOneDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
