// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "userapi/models"
)

// DeleteOneNoContentCode is the HTTP code returned for type DeleteOneNoContent
const DeleteOneNoContentCode int = 204

/*DeleteOneNoContent Deleted

swagger:response deleteOneNoContent
*/
type DeleteOneNoContent struct {
}

// NewDeleteOneNoContent creates DeleteOneNoContent with default headers values
func NewDeleteOneNoContent() *DeleteOneNoContent {

	return &DeleteOneNoContent{}
}

// WriteResponse to the client
func (o *DeleteOneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteOneNotFoundCode is the HTTP code returned for type DeleteOneNotFound
const DeleteOneNotFoundCode int = 404

/*DeleteOneNotFound User Not Found

swagger:response deleteOneNotFound
*/
type DeleteOneNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOneNotFound creates DeleteOneNotFound with default headers values
func NewDeleteOneNotFound() *DeleteOneNotFound {

	return &DeleteOneNotFound{}
}

// WithPayload adds the payload to the delete one not found response
func (o *DeleteOneNotFound) WithPayload(payload *models.Error) *DeleteOneNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete one not found response
func (o *DeleteOneNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOneNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
