// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchOneHandlerFunc turns a function with the right signature into a patch one handler
type PatchOneHandlerFunc func(PatchOneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchOneHandlerFunc) Handle(params PatchOneParams) middleware.Responder {
	return fn(params)
}

// PatchOneHandler interface for that can handle valid patch one params
type PatchOneHandler interface {
	Handle(PatchOneParams) middleware.Responder
}

// NewPatchOne creates a new http.Handler for the patch one operation
func NewPatchOne(ctx *middleware.Context, handler PatchOneHandler) *PatchOne {
	return &PatchOne{Context: ctx, Handler: handler}
}

/*PatchOne swagger:route PATCH /user/{id} users patchOne

PatchOne patch one API

*/
type PatchOne struct {
	Context *middleware.Context
	Handler PatchOneHandler
}

func (o *PatchOne) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchOneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
