// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "userapi/models"
)

// PatchOneOKCode is the HTTP code returned for type PatchOneOK
const PatchOneOKCode int = 200

/*PatchOneOK Patch user with specific id

swagger:response patchOneOK
*/
type PatchOneOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchOneOK creates PatchOneOK with default headers values
func NewPatchOneOK() *PatchOneOK {

	return &PatchOneOK{}
}

// WithPayload adds the payload to the patch one o k response
func (o *PatchOneOK) WithPayload(payload *models.User) *PatchOneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch one o k response
func (o *PatchOneOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchOneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
