swagger: "2.0"
info:
  description: Implementing a User API with a Cassandra backend
  title: A User API with Cassandra backend
  version: 1.0.0
produces:
- application/json
consumes:
- application/json
schemes:
- http
paths:
  /user:
    get:
      tags:
        - users
      operationId: getAll
      responses:
        200:
          description: List the users
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        404:
          description: Users Not Found
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - users
      operationId: createOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/user"
        400:
          description: Invalid Form Data - Bad Request
          schema:
            $ref: "#/definitions/error"
  /user/{id}:
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      tags:
        - users
      operationId: getOne
      responses:
        200:
          description: User with specific id
          schema:
            $ref: "#/definitions/user"
        404:
          description: User Not Found
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - users
      operationId: deleteOne
      responses:
        204:
          description: Deleted
        404:
          description: User Not Found
          schema:
            $ref: "#/definitions/error"
    patch:
      tags:
        - users
      operationId: patchOne
      parameters:
      - name: body
        in: body
        schema:
          $ref: "#/definitions/patchDocument"
      responses:
        200:
          description: Patch user with specific id
          schema:
            $ref: "#/definitions/user"
        400:
          description: Invalid Patch Form - Bad Request
          schema:
            $ref: "#/definitions/error"
        404:
          description: User Not Found
          schema:
            $ref: "#/definitions/error"
        default:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    required:
    - first_name
    - last_name
    - email
    properties:
      id:
        type: string
        readOnly: true
      first_name:
        type: string
        minLength: 3
      last_name:
        type: string
        minLength: 3
      email:
        type: string
        format: email
        minLength: 6
  patchDocument:
    type: object
    properties:
      first_name:
        type: string
        minLength: 3
      last_name:
        type: string
        minLength: 3
      email:
        type: string
        format: email
        minLength: 6
  error:
    type: object
    required:
    - status
    properties:
      status:
        type: string
